language: node_js
node_js:
- '8.6.0'
sudo: false
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before_script:
- sleep 15
script:
- npm test
- ./install.sh
after_success:
- git config --global user.email "travis@localhost.localdomain"
- git config --global user.name "Travis CI"
- git checkout -b master
- git add --all
- git commit -am "Travis change"
