language: node_js
node_js:
- '0.10'
before_install:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
- echo 'deb http://repo.mongodb.org/apt/ubuntu '$(lsb_release -sc)'/mongodb-org/3.0
  multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
- sudo apt-get update
- sudo apt-get install -y mongodb-org-server
before_script:
- until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
script:
- npm test
- ./install.sh
after_success:
- git config --global user.email "travis@localhost.localdomain"
- git config --global user.name "Travis CI"
- git checkout -b master
- git add --all
- git commit -am "Travis change"
deploy:
  - provider: openshift
    user: pedpral@gmail.com
    password:
      secure: T4Aqzxdf0OAZs+DrDT75FztoDAV4Eo7xr3ylEys1riC4K166JWbXmrt0+cT7Mkg9Qodvq+cixJOhdTEPQMooQKTZI1aJSJyjIP4cZfy0d7pm+44cmoNeiVcmL+jvxYZnPmQy4Mtcx02ZaKyO6LTuFotHWmH9/Fm4opXorB23L44=
    app: gestionfct
    domain: pedroprieto
    on: master
    skip_cleanup: true
  - provider: openshift
    user: tics@iesmarenostrum.com
    password:
      secure: TTeOF0XD86Pxu5Hds5zipxyubtAxRG53ZX8MX/4MRf8esWg0qNfnu5gFMQBzNym5YtFrfLHOZ+DLNEv99Wov4WfCJcFJm9upfFwJqhdObqwGKDxhTvp/VINRrEZuks4Rf9wK21mV4IXYr3jbzvjNgEjUGxdYggRjsFH8UyexwHw=
    app: gestionfct
    domain: marenostrum
    on: production
    skip_cleanup: true
    edge: true
