language: node_js
node_js:
- '0.10'
sudo: false
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before_script:
- sleep 15
script:
- npm test
- ./install.sh
after_success:
- git config --global user.email "travis@localhost.localdomain"
- git config --global user.name "Travis CI"
- git add --all
- git commit -am "Travis change"
deploy:
  provider: openshift
  user: pedpral@gmail.com
  password:
    secure: T4Aqzxdf0OAZs+DrDT75FztoDAV4Eo7xr3ylEys1riC4K166JWbXmrt0+cT7Mkg9Qodvq+cixJOhdTEPQMooQKTZI1aJSJyjIP4cZfy0d7pm+44cmoNeiVcmL+jvxYZnPmQy4Mtcx02ZaKyO6LTuFotHWmH9/Fm4opXorB23L44=
  app: gestionfct
  domain: pedroprieto
  skip_cleanup: true
