version = 0.1
[default.deploy.parameters]
stack_name = "gestion-fct"
resolve_s3 = true
s3_prefix = "gestion-fct"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\" ApiName=\"gestionfct\""
image_repositories = []
